if(EXISTS "/home/andu/web/turing_tests/practice/paranthesis[1]_tests.cmake")
  include("/home/andu/web/turing_tests/practice/paranthesis[1]_tests.cmake")
else()
  add_test(paranthesis_NOT_BUILT paranthesis_NOT_BUILT)
endif()
